spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/musicdb

jwt:
  secret: your-256-bit-secret
  issuer: music-catalog-api
  expirationInMs: 86400000 # 24 hours

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method