spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/musicdb

logging:
  level:
    com.musiccatalog: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG